[package]
name = "whisper-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
bytes = "1.8.0"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
ed25519-dalek = { version = "2.1.1", features = ["pem", "signature"] }
env_logger = "0.11.5"
fastwebsockets = { version = "0.8.0", features = ["unstable-split", "upgrade"] }
tokio-rustls = { version = "0.26.0", default-features = false, features = ["tls12", "ring"] }
http-body-util = "0.1.2"
hyper = { version = "1.5.0", features = ["client"] }
hyper-util = { version = "0.1.9", features = ["tokio"] }
log = { version = "0.4.22", features = ["std", "serde"] }
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = ["full"] }
tun2 = { version = "3.1.8", features = ["async"] }
webpki-roots = "0.26.6"
whisper = { version = "*", path = "../lib" }
wisp-mux = { workspace = true, features = ["fastwebsockets"] }
tokio-util = "0.7.12"

